### ISSUE TITLE
Unnecessary Dependency 

### ISSUE THREAD

**Issue by SpiderMath** [nahann/Shiba#19]
In the [package.json](https://github.com/nahann/Shiba/blob/master/package.json#L8) of the project, I found a dependency named `fs`. But as far as I could find, fs is a **built in** module in Node.js and the package registered under the name of fs, is basically a `security` version, to occupy the spot, since the previous one was removed.

To quote NPM,
```
Security holding package
This package name is not currently in use, but was formerly occupied by another package. To avoid malicious use, npm is hanging on to the package name, but loosely, and we'll probably give it to you if you want it.
```

You will find what I am talking about [here](https://www.npmjs.com/package/fs). 
Also, to prove my point about it being a bundled dependency with Node, you can read the package docs in [here](https://nodejs.org/api/fs.html) which is the official Node.js documentation.

So you might wanna remove this dependency!
~~Don't kill me for this Lesi~~

**Comment by noraclegit** [comment]
removed this, and will definitely kill you
